export const blockOptions = [
  { value: "anandi", label: "Anandi"},
  { value: "aryabhatta", label: "Aryabhatta" },
  { value: "bhaskara", label: "Bhaskara" },
  { value: "brahmagupta", label: "Brahmagupta" },
  { value: "charaka", label: "Charaka" },
  { value: "gargi", label: "Gargi" },
  { value: "kapila", label: "Kapila" },
  { value: "kautilya", label: "Kautilya" },
  { value: "maitreyi", label: "Maitreyi" },
  { value: "ramanuja", label: "Ramanuja" },
  { value: "susruta", label: "Susruta" },
  { value: "varahamihira", label: "Varahamihira" },
  { value: "vyasa", label: "Vyasa" },
  { value: "raman", label: "Raman" },
  { value: "ramanujan", label: "Ramanujan" },
  { value: "kalam", label: "Kalam" },
  { value: "sarabhai", label: "Sarabhai" },
  { value: "bhabha", label: "Bhabha" },
  { value: "visvesvaraya", label: "Visvesvaraya" },
  { value: "vivekananda", label: "Vivekananda" },
  { value: "sn-bose", label: "SN Bose" },
  { value: "sarojini_naidu", label:"Sarojini Naidu"},
];

export const eventOptions = [
[
  { value: "solo-dance", label: "Solo Dance" },
  { value: "duo-trio-dance", label: "Duo Trio Dance" },
  { value: "group-dance", label: "Group Dance" },
  { value: "street-battle", label: "Street Battle" },
  { value: "film-making-75-hours", label: "Film Making 75 hours" },
  { value: "make-it-short", label: "Make it short" },
  { value: "ad-making", label: "Ad Making" },
  { value: "theme-based-photography", label: "Theme Based Photography" },
  { value: "photo-story-challenge", label: "Photo Story Challenge" },
  { value: "live-photo-challenge", label: "Live Photo Challenge" },
  { value: "stage-play", label: "Stage Play" },
  { value: "achanak-se-points-badal-diye", label: "Achanak se points badal diye" },
  { value: "stand-up", label: "Stand Up" },
  { value: "graffiti-painting", label: "Graffiti Painting" }, 
  { value: "clay-modelling", label: "Clay Modelling" },
  { value: "weave-a-tale", label: "Weave-a-Tale" },
  { value: "english-poetry-writing", label: "English Poetry Writing" },
  { value: "general-quiz", label: "General Quiz" },
  { value: "scrabble", label: "Scrabble" },
  { value: "treasure-hunt", label: "Treasure Hunt" },
  { value: "british-parliamentary", label: "British Parliamentary" },
  { value: "bmc-pictionary", label: "BMC Pictionary" },
  { value: "codenames", label: "Codenames" },
  { value: "solo-singing", label: "Solo Singing" },
  { value: "freestyle", label: "Freestyle" },
  { value: "antakshari", label: "Antakshari" },
  { value: "battle-of-bands", label: "Battle of Bands" },
  { value: "cosplay-showdown", label: "Cosplay Showdown" },
  { value: "animanga-quiz", label: "Animanga Quiz" },
  { value: "hackathon-lambda", label: "Hackathon (Lambda)" },
  { value: "drop-the-egg-challenge", label: "Drop the Egg Challenge" },
  { value: "water-rocketry", label: "Water Rocketry" },
  { value: "gridlock", label: "Gridlock" },
  { value: "milan-ctf24", label: "Milan CTF24" },
  { value: "astro-photography-competition", label: "Astro Photography Competition" },
  { value: "quiz-competition", label: "Quiz Competition" },
  { value: "hackathon-prakriti", label: "Hackathon (Prakriti)" },
  { value: "elektronica", label: "Elektronica" },
  { value: "inverted-pendulum", label: "Inverted Pendulum" },
  { value: "esports-and-gamedev", label: "Esports and Gamedev" },
  { value: "clash-royale", label: "Clash Royale" },
  { value: "bgmi", label: "BGMI" },
  { value: "valorant", label: "Valorant" },
  { value: "cod-m", label: "COD-M" },
  { value: "carrom", label: "Carrom" },
  { value: "hockey", label: "Hockey" },
  { value: "volleyball", label: "Volleyball" },
  { value: "8-ball-pool", label: "8 Ball Pool" },
  { value: "basketball", label: "Basketball" },
  { value: "athletics", label: "Athletics" },
  { value: "cricket", label: "Cricket" },
  { value: "football", label: "Football" },
  { value: "dodgeball", label: "Dodgeball" },
  { value: "chess", label: "Chess" },
  { value: "powerlifting", label: "Powerlifting" },
  { value: "weightlifting", label: "Weightlifting" },
  { value: "squash", label: "Squash" },
  { value: "badminton", label: "Badminton" },
  { value: "table-tennis", label: "Table Tennis" },
  { value: "lawn-tennis", label: "Lawn Tennis" },
  { value: "aquatics", label: "Aquatics" },
  { value: "mad-over-marketing", label: "Mad Over Marketing" },
  { value: "battle-of-debts", label: "Battle of Debts" },
  { value: "solve-the-case", label: "Solve the Case" }
]

];