export const blockOptions = [
  { value: "aryabhatta", label: "Aryabhatta" },
  { value: "bhaskara", label: "Bhaskara" },
  { value: "brahmagupta", label: "Brahmagupta" },
  { value: "charaka", label: "Charaka" },
  { value: "gargi", label: "Gargi" },
  { value: "kapila", label: "Kapila" },
  { value: "kautilya", label: "Kautilya" },
  { value: "maitreyi", label: "Maitreyi" },
  { value: "ramanuja", label: "Ramanuja" },
  { value: "susruta", label: "Susruta" },
  { value: "varahamihira", label: "Varahamihira" },
  { value: "vyasa", label: "Vyasa" },
  { value: "raman", label: "Raman" },
  { value: "ramanujan", label: "Ramanujan" },
  { value: "kalam", label: "Kalam" },
  { value: "sarabhai", label: "Sarabhai" },
  { value: "bhabha", label: "Bhabha" },
  { value: "visvesvaraya", label: "Visvesvaraya" },
];

export const eventOptions = [
  { value: "freestyle", label: "Freestyle" },
  { value: "solo-singing", label: "Solo singing" },
  { value: "band-competition", label: "Band competition" },
  { value: "stage-play-the-drama-duel", label: "Stage play - The drama duel" },
  { value: "pictionary", label: "Pictionary" },
  { value: "tricube-writing", label: "Tricube writing" },
  { value: "scrabble", label: "Scrabble" },
  { value: "photo-manipulation", label: "Photo manipulation" },
  { value: "not-so-sorry", label: "Not so sorry" },
  { value: "reel-making-contest", label: "Reel making contest" },
  { value: "monochrome-photography", label: "Monochrome photography" },
  {
    value: "karl-popper-standard-debate",
    label: "Karl Popper (Standard debate)",
  },
  {
    value: "achanak-se-points-badal-diye",
    label: "Achanak se points badal diye",
  },
  { value: "treasure-hunt", label: "Treasure hunt" },
  {
    value: "close-up-portrait-photography",
    label: "Close up portrait photography",
  },
  { value: "general-quiz", label: "General quiz" },
  { value: "a-diary-from-the-future", label: "A diary from the future" },
  { value: "bmc-codenames", label: "BMC codenames" },
  { value: "pass-the-painting", label: "Pass the painting" },
  { value: "street-battle", label: "Street Battle" },
  { value: "film-making-competition", label: "Film making competition" },
  { value: "duo-trio", label: "Duo Trio" },
  { value: "group-dance", label: "Group dance" },
  { value: "solo-dance", label: "Solo Dance" },
  { value: "crude-radio-building", label: "Crude radio-building" },
  { value: "robo-art", label: "Robo Art" },
  { value: "propeller-car-race", label: "Propeller Car Race" },
  { value: "sugar-rocketry", label: "Sugar Rocketry" },
  { value: "capture-the-flag", label: "Capture the Flag" },
  { value: "game-jam", label: "Game Jam" },
  { value: "hackathon-epoch", label: "Hackathon-Epoch" },
  { value: "hackathon-lambda", label: "Hackathon-Lambda" },
  { value: "codeopardy", label: "Codeopardy" },
  {
    value: "simulation-of-three-body-problem",
    label: "Simulation of three body problem",
  },
  { value: "tinkerers", label: "Tinkerer's" },
  { value: "prakritis", label: "Prakriti's" },
  { value: "esports", label: "Esports" },
  { value: "hockey", label: "Hockey" },
  { value: "table-tennis", label: "Table Tennis" },
  { value: "lawn-tennis", label: "Lawn Tennis" },
  { value: "volleyball", label: "Volleyball" },
  { value: "cricket", label: "Cricket" },
  { value: "badminton", label: "Badminton" },
  { value: "football", label: "Football" },
  { value: "carrom", label: "Carrom" },
  { value: "chess", label: "Chess" },
  { value: "squash", label: "Squash" },
  { value: "weightlifting", label: "Weightlifting" },
  { value: "basketball", label: "Basketball" },
  { value: "dodgeball", label: "Dodgeball" },
  { value: "athletics", label: "Athletics" },
];
